### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cozyplanes**

### CODE REVIEW

**Comment by cozyplanes** [comment]
I am cozyplanes not Cozyplanes

just worth mentioning...

**Comment by Skayo** [comment]
Oh sorry

**Comment by Kimmax** [comment]
Did you just complain that he capitalized your name? lmao
This is gold

**Comment by cozyplanes** [comment]
@Kimmax never complained

**Comment by Kimmax** [comment]
@cozyplanes you really really really need to work on your expressions, sometimes you sound really really sassy and pissed off over the most basic things, that tend to get ppl even more pissed

**Comment by cozyplanes** [comment]
@Kimmax 🆗 maybe cuz i use short words and not sentences. sorry

**Comment by cozyplanes** [comment]
🤣

**Pull request merged**
